before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6

matrix:
  fast_finish: true

  include:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
